### ISSUE TITLE
"Dockerfile" file and "dockerfile" directory conflict on case insensitive filesystems.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/srclib-docker#1]
The root folder of this repo contains a file `Dockerfile`. It also contains a folder `dockerfile` that has two .go files in it.

This is fine on case sensitive filesystems (mostly a default of Linux), but both cannot exist at the same time on case insensitive filesystems (default of OS X, Windows).

If you try to check out one, it removes the other:

```bash
srclib-docker $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Dockerfile

no changes added to commit (use "git add" and/or "git commit -a")
srclib-docker $ git checkout -- Dockerfile
srclib-docker $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    dockerfile/dockerfile.go
	deleted:    dockerfile/dockerfile_test.go

no changes added to commit (use "git add" and/or "git commit -a")
srclib-docker $ 
```

I'm not sure what a good solution would be. `dockerfile` seems like a good name for the package. Is it possible to rename `Dockerfile` to something custom and specify that it is custom rather than the default? I know it's possible with `Makefile`s, for example `make -f custom-Makefile-name`.

**Comment by shurcooL** [comment]
> I'm not sure what a good solution would be. `dockerfile` seems like a good name for the package. Is it possible to rename `Dockerfile` to something custom and specify that it is custom rather than the default? I know it's possible with `Makefile`s, for example `make -f custom-Makefile-name`.

One suggestion was to rename the Go package from `dockerfile` to `docker_file` or so. It seems less than ideal having to pick an inferior Go package name, but it may be the lesser evil?

**Comment by sqs** [comment]
SGTM

Or dockerfile2. Your call.
